### PR TITLE
Moved LESS to dev dependencies and further decreased package size

### PR DESCRIPTION
**Pull request by rafaelklaessen**
Hi,
Thanks for making circular-std available via the npm registry. I appreciate your work tremendously.

One small thing I noticed upon installing this package, though, is that it also installs LESS. This is unnecessary since LESS is only used in development, yet it still installs several megabytes of dependencies. This is a shame, I think.

Would you please merge this PR? Only changes are in package.json...I moved LESS to the dev dependencies and also tweaked the files field to only upload the dist folder.

Thanks!

### CODE REVIEW

**Comment by bcomnes** [comment]
Would love to see this land!

**Comment by bcomnes** [comment]
I released a scoped fork: https://www.npmjs.com/package/@css-pkg/circular-std

Happy to collaborate in the future if it makes sense :)

**Comment by ixahmedxi** [comment]
hey!,
I will look into it and get back to you, always down for a collaboration :)

**Comment by ixahmedxi** [comment]
Thanks for the PR! Great job <3

**Pull request merged**
